[package]
name = "compiler_driver"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
lexer = { path = "../lexer" }
parser = { path = "../parser" }
codegen = { path = "../codegen" }
emitter = { path = "../emitter" }
